---
label: Site Config
hide_body: false
fields:
- name: pathPrefix
  label: Pathprefix
  type: text
  hidden: false
  default: ''
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: textarea
  hidden: false
  default: ''
